name: Publish NuGet Package

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore Dependencies
        run: dotnet restore ResultKit.slnx

      - name: Build Solution
        run: dotnet build ResultKit.slnx --configuration Release --no-restore

      - name: Run Unit Tests
        run: dotnet test Tests/Tests.csproj --configuration Release --no-build

      - name: Pack ResultKit
        run: dotnet pack ResultKit/ResultKit.csproj --configuration Release --no-build --output ./nupkg

      - name: Publish To NuGet
        run: |
          dotnet nuget push "./nupkg/*.nupkg" \
            --api-key "${{ secrets.NUGET_API_KEY }}" \
            --source "https://api.nuget.org/v3/index.json" \
            --skip-duplicate